### ISSUE TITLE
Create 2D GCM encoding mechanism

### ISSUE THREAD

**Issue by rhyolight** [htm-community/htm-2d-object-modeling#1]
Given an XY location in the environment, this layer should represent this space in many Grid Cell Modules, which work together to resolve the object. This is not an encoder (like the HTM School videos imply). This layer must run GCMs that will respond to displacement vectors appropriately. 

The only property these SDRs in this layer must have is consistent displacements between them, which will enable movements through the space to have meaning no matter where they originate. 

To test this, let's assume an XY space that is 10 units square. 
The SDR for location 2,2 is A, and the SDR for location 2,3 is B. The displacement A-B is d1.
The SDR for location 3,2 is C, and the SDR for location 3,3 is D. The displacement C-D is d2.

assert d1 == d2

Something like that. I need to review the [Columns+](https://numenta.com/neuroscience-research/research-publications/papers/locations-in-the-neocortex-a-theory-of-sensorimotor-object-recognition-using-cortical-grid-cells/) paper to provide more details.

**Comment by SimLeek** [comment]
Are you trying to make an attractor network, like this one, but in a 2D grid?

![example](https://openi.nlm.nih.gov/imgs/512/324/3995086/PMC3995086_gr3.png)

Actually, none of the images on google seem to be that close. Let me draw something up in gimp...

**Comment by SimLeek** [comment]
Here's what I'm thinking:

![stationary motor feature](https://user-images.githubusercontent.com/5911683/53142943-1f961d00-3553-11e9-882c-aa5df48ab82e.png)

![moving motor feature](https://user-images.githubusercontent.com/5911683/53142946-21f87700-3553-11e9-8391-d49663dafcfa.png)

Additionally, this displacement layer should employ the same 'multiple layers with different scales' optimization of the entorhinal grid cells, right? Like this:

![image](https://user-images.githubusercontent.com/5911683/53143081-bc58ba80-3553-11e9-8212-b98010de0a99.png)

**Comment by SimLeek** [comment]
If the last post is correct, you should be able to run a convolution operation of the displacement layer on the feature layer and get the moved feature layer.

**Comment by SimLeek** [comment]
Note: Sorry for so many posts, but my pysilent package may approach this:

![image](https://user-images.githubusercontent.com/5911683/53143880-32125580-3557-11e9-8640-92012cd05a37.png)

Circled in red, I get the 'centroids' of the features I detect (which are circled in blue). Adding value back in may make it closer to the image and increase sparsity, and running off of only 1 channel should increase sparsity as well, while also working with certain features (orientation in this case, but I can have 'orientation' in 2D too).

**Comment by marty1885** [comment]
@rhyolighy If I read your post correctly. Therefore C + d1 = D?

**Comment by rhyolight** [comment]
@SimLeek You are on the right track, but I highly suggest you review the [supplemental materials to the Frameworks Paper](https://www.frontiersin.org/articles/10.3389/fncir.2018.00121/full#supplementary-material) before you continue.

**Comment by SimLeek** [comment]
Read it for lunch break. If it were used on vision, it seems like it'd be like sift, but with relative local positions instead of local orientations.

**Comment by rhyolight** [comment]
I just had a meeting with Jeff and the research team, and I was totally misleading you guys with this task. There is no reason to have displacements in this project at this point. I'm going to close this and clarify the remaining tasks.
